// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbalWVKQ8o_JS-TVcWj7dXZIr7AB7UY2o',
    appId: '1:750053333393:android:5356dfaf6ea4e366502230',
    messagingSenderId: '750053333393',
    projectId: 'coa-main',
    storageBucket: 'coa-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJboquixz1tR2va3OINHNm8bhlOH1T3Sg',
    appId: '1:750053333393:ios:8d4e2ebcd504a087502230',
    messagingSenderId: '750053333393',
    projectId: 'coa-main',
    storageBucket: 'coa-main.firebasestorage.app',
    iosBundleId: 'com.example.pro1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSI589cyfvdle16uXcBokX3zXqOWbKq9Q',
    appId: '1:750053333393:web:0860f8e1d4f2ef45502230',
    messagingSenderId: '750053333393',
    projectId: 'coa-main',
    authDomain: 'coa-main.firebaseapp.com',
    storageBucket: 'coa-main.firebasestorage.app',
    measurementId: 'G-N05K7XTWY6',
  );

}